package com.rsa.telemetry.data

import com.rsa.telemetry.capture.Acceleration
import com.rsa.telemetry.capture.TelemetryPacket
import com.rsa.telemetry.queue.PacketStatus
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Room entities are plain annotated data classes with no Android platform dependency, so the
 * wire-format <-> local-row mapping is exercised here on the JVM rather than as an instrumented
 * DAO test (see README for what still needs a real device/emulator).
 */
class PacketEntityMappingTest {

    private val samplePacket = TelemetryPacket(
        packetId = "11111111-1111-1111-1111-111111111111",
        deviceId = "22222222-2222-2222-2222-222222222222",
        capturedAt = "2026-09-05T14:32:01.000Z",
        lat = -34.6037,
        lon = -58.3816,
        altitudeM = 1200.5,
        gpsAccuracyM = 8.2,
        speedMps = 42.3,
        headingDeg = 187.4,
        acceleration = Acceleration(x = 0.12, y = -0.03, z = 9.81),
        batteryPct = 76,
    )

    @Test
    fun `entity round-trips back to an identical packet`() {
        val entity = samplePacket.toEntity(capturedAtEpochMillis = 1_800_000_000_000L)

        assertEquals(samplePacket, entity.toPacket())
    }

    @Test
    fun `new entities default to PENDING status`() {
        val entity = samplePacket.toEntity(capturedAtEpochMillis = 1_800_000_000_000L)

        assertEquals(PacketStatus.PENDING.name, entity.status)
    }

    @Test
    fun `entity keeps the epoch millis it was given, separately from the formatted string`() {
        val entity = samplePacket.toEntity(capturedAtEpochMillis = 1_800_000_000_000L)

        assertEquals(1_800_000_000_000L, entity.capturedAtEpochMillis)
        assertEquals("2026-09-05T14:32:01.000Z", entity.capturedAt)
    }

    @Test
    fun `packet id is preserved verbatim, never regenerated by the mapping`() {
        val entity = samplePacket.toEntity(capturedAtEpochMillis = 1_800_000_000_000L)

        assertEquals(samplePacket.packetId, entity.packetId)
    }
}
